---
- name: Limpia inventario de elementos configuracion rfcs aplicar
  hosts: localhost
  gather_facts: false
  collections:
      - awx.awx
  tasks:

  - name: bloque borra inventario elemento configuracion 
    block:

    - name: trae datos del elemento de configuracion 
      uri:
        url: "{{varsflujo_invar_host}}/api/now/v1/table/cmdb_ci/{{varsflujo_elementoconfig}}"
        url_username: '{{varsflujo_invar_username}}'
        url_password: '{{varsflujo_invar_password}}'
        force_basic_auth: yes
        validate_certs: no
        method: GET
      register: elemento_config 

    - name: borra host
      host:
        name: "{{elemento_config['json']['result']['name']}}"
        description: "Elemento configuracion RFC"
        inventory: "INV_IBMI_RFCS"
        state: absent
        validate_certs: no
        variables:
          ansible_host: "{{elemento_config['json']['result']['ip_address']}}"
          ansible_python_interpreter: "/QOpensys/pkgs/bin/python3"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          group_names: ['IBMi']


    when: staging | bool == false

  - name: bloque borra inventario elemento configuracion Staging 
    block:

      - name: borra host
        host:
          name: "{{host_staging}}"
          description: "Elemento configuracion Staging RFC"
          inventory: "INV_IBMI_RFCS"
          state: absent
          validate_certs: no
          variables:
            ansible_host: "{{host_staging}}"
            ansible_python_interpreter: "/QOpensys/pkgs/bin/python3"
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
            group_names: ['IBMi']
            
    when: staging | bool == true



